# Generated by Django 4.0 on 2023-06-23 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='measure',
        ),
    ]
