# Generated by Django 4.0 on 2023-06-22 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=255)),
                ('user_fk', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'permissions': [('custom_add_stock', 'Can add stock'), ('custom_change_stock', 'Can change the stock'), ('custom_delete_stock', 'Can delete the stock')],
            },
        ),
    ]
