# Generated by Django 4.0 on 2023-06-23 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('stock', '0002_alter_stock_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='user_fk',
        ),
        migrations.AddField(
            model_name='stock',
            name='product_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='stock',
            name='supplie_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.supplier'),
        ),
    ]
